package com.pamungkas.submission

object DataMakanan {
    private val makananNames = arrayOf(
        "Bakso", "Ayam Geprek", "Ayam Bakar", "Gurame Bakar", "Capcay Goreng", "Kwetiau", "Mie Ayam", "Mie Goreng", "Nasi Goreng", "Tekwan"
    )
    private val makananPrice = intArrayOf(
        9_000, 10_000, 11_000, 21_000, 12_000, 14_000, 10_000, 7_000, 10_000, 10_000
    )
    private val makananDetail = arrayOf(
        "Bakso atau baso adalah jenis bola daging yang lazim ditemukan pada masakan Indonesia. Bakso umumnya dibuat dari campuran daging sapi giling dan tepung tapioka, tetapi ada juga bakso yang terbuat dari daging ayam, ikan, atau udang bahkan daging kerbau. Dalam penyajiannya, bakso umumnya disajikan panas-panas dengan kuah kaldu sapi bening, dicampur mi, bihun, taoge, tahu, terkadang telur lalu ditaburi bawang goreng dan seledri. Bakso sangat populer dan dapat ditemukan di seluruh Indonesia; dari gerobak pedagang kaki lima hingga restoran besar. Berbagai jenis bakso sekarang banyak ditawarkan dalam bentuk makanan beku yang dijual di pasar swalayan ataupun mal-mal. Irisan bakso dapat juga dijadikan pelengkap jenis makanan lain seperti mi goreng, nasi goreng, atau capcai.",
        "Ayam geprek (Hanacaraka:ꦄꦪꦩ꧀​ꦒꦼꦥꦽꦏ꧀) adalah makanan ayam goreng tepung khas Indonesia yang diulek atau dilumatkan bersama sambal bajak. Kini ayam geprek telah menjadi hidangan populer yang dapat ditemukan di hampir semua kota besar di Indonesia, tetapi asal mula ayam geprek berasal dari kota Yogyakarta. Geprek adalah istilah dalam Bahasa Jawa yang berarti dipukul, ditekan, atau dilumatkan, maka ayam geprek berarti ayam yang dipukul. Hidangan ini mirip dengan masakan Jawa tradisional ayam penyet, karena keduanya adalah sama-sama ayam goreng yang dipukul dan ditekan dengan menggunakan ulekan dan dicampur dengan sambal. Perbedaannya adalah, ayam penyet adalah ayam goreng tradisional Jawa yang diungkep dengan bumbu kuning, kemudian digoreng rendam dalam minyak goreng panas. Sementara ayam geprek lebih mirip dengan ayam goreng gaya barat (lazim disebut fried chicken Amerika), yakni ayam goreng tepung yang renyah yang dilapisi dengan adonan tepung terigu sebelum digoreng.",
        "Ayam bakar adalah sebuah hidangan Asia Tenggara Maritim, terutama hidangan Indonesia atau Malaysia, dari ayam yang dipanggang di atas arang. Di Jawa , ayam biasanya direndam dengan campuran kecap manis (kecap manis) dan minyak kelapa , dioleskan dengan sikat saat dipanggang. Bumbu campuran rempah-rempah dapat bervariasi antar daerah, tetapi biasanya terdiri dari kombinasi tanah bawang merah , bawang putih , cabai , ketumbar , asam jus, kemiri , kunyit , lengkuas dan garam. Di Jawa, ayam bakar biasanya terasa agak manis karena banyaknya kecap manis baik sebagai bumbu perendam atau saus celup, sedangkan ayam bakar Padang ,Bali , dan rempah-rempah lainnya, dan tidak adanya kecap manis.Lombok dan sebagian besar Sumatera biasanya lebih pedas dan lebih kemerahan karena banyaknya cabai, kunyit. Potongan ayam biasanya dimasak sebagian dalam campuran bumbu menggunakan api kecil sebelum dipanggang, agar ayam menyerap bumbu. Selama proses pemanggangan, sisa bumbu dioleskan pada ayam. Ayam bakar biasanya disajikan dengan sambal terasi (cabai dengan terasi ) atau sambal kecap (irisan cabai dan bawang merah dalam kecap manis) sebagai saus atau bumbu dan irisan ketimun dan tomat sebagai hiasan.",
        "Ikan bakar adalah hidangan ikan yang dibakar atau dipanggang di atas api atau bara api. Hidangan ikan yang dibakar, muncul secara universal di berbagai belahan dunia. Akan tetapi secara khusus di dunia internasional, istilah ikan bakar merujuk kepada ikan bakar khas Indonesia dan Malaysia berupa ikan atau boga bahari lain yang dipanggang di atas arang atau bara api. Ikan bakar adalah salah satu hidangan klasik Indonesia. Sebagai negara kepulauan, ikan bakar sangat populer di Indonesia dan dapat ditemui di berbagai tempat, mulai dari kedai di tepi pantai Aceh, restoran di tepi pantai Kupang, sampai ke pusat kota Jakarta. Berbagai resep ikan bakar spesifik muncul, seperti ikan bakar Cianjur khas Sunda, yang umumnya menggunakan ikan air tawar seperti ikan mas dan gurami, serta ikan bakar Jimbaran khas Bali, yang disajikan di beberapa warung di sekitar pantai dan pasar ikan di Jimbaran, Bali. Ikan bakar laut, secara khusus populer di kawasan Indonesia Timur; seperti Sulawesi dan Maluku di mana kebanyakan penduduknya bekerja sebagai nelayan, dan kawasan ini memiliki laut yang luas yang menghasilkan banyak jenis boga bahari. Biasanya, ikan direndam bumbu dengan campuran bumbu halus, kadang dengan campuran terasi atau kecap manis dan kemudian dipanggang; terkadang alat pemanggang dilapisi daun pisang agar ikan tidak rusak dan hancur ketika dibalik akibat ikan lengket dan melekat di alat pemanggang.",
        "Capcai (Hanzi: 雜菜; Pinyin: zácài; Pe̍h-ōe-jī: cha̍p-chhài; aneka sayuran) atau capcay adalah nama hidangan khas Tionghoa-Indonesia berupa banyak macam sayuran yang dimasak dengan cara direbus (kuah) atau digoreng tumis. Capcai asal mulanya merupakan variasi dari hidangan khas Fujian. Nama capcai diambil dari dialek Hokkian yang secara harfiah berarti aneka ragam sayur.Jumlah sayuran dalam capcai tidak tentu, tetapi banyak yang salah kaprah mengira bahwa capcai harus mengandung 10 macam sayuran karena secara harfiah adalah berarti sepuluh sayur. Cap di dalam dialek Hokkian juga dapat dieja sepuluh, dan cai berarti sayur. Beberapa jenis sayuran yang biasanya dicampur dalam capcai adalah sawi putih, sawi hijau, wortel, jagung muda, jamur merang, jamur kuping, kol, kapri, buncis, bunga kol, brokoli, daun bawang, tomat, dan bawang bombay. Walaupun demikian, unsur protein hewani juga biasa ditambahkan ke dalam makanan ini, misalnya daging sapi, ayam, telur, hati dan ampela ayam, udang, bakso, cumi-cumi, dan daging babi.",
        "Kwetiau (Hanzi: 粿條, hanyu pinyin: guotiao, juga disebut 沙河粉, shā hé fěn) adalah sejenis mi Tionghoa berwarna putih yang terbuat dari beras. Kwetiau merupakan makanan yang cukup populer di Indonesia, terutama di Jakarta dan tempat-tempat lain yang banyak didiami warga keturunan Tionghoa. Kwetiau pada umumnya identik dengan orang Tionghoa etnis Hokkian dan Tio Ciu. Di Indonesia, kwetia dibedakan atas kwetiau masakan etnis Hokkian dan kwetiau masakan etnis Tio Ciu. Kwetiau yang terkenal di kalangan Etnis Hokkian yang banyak berdiam di Sumatra adalah kwetiau medan yang memakai bakso ikan, lapchiong (sosis babi), dan telur bebek. Kwetiau yang terkenal di kalangan etnis Tio Ciu yang banyak berdiam di Kalimantan adalah kwetiau sapi yang memakai daging sapi beserta jeroannya seperti babat. Dalam perkembangannya muncul varian baru yang dikenal dengan sebutan kwetiau siram. Kwetiau Siram adalah jenis kwetiau yang berkuah, sering dimasak dengan daging babi ataupun sapi.",
        "Mi ayam atau bakmi ayam adalah masakan Indonesia yang terbuat dari mi kuning direbus mendidih kemudian ditaburi saus kecap khusus beserta daging ayam dan sayuran. Mi ayam terkadang ditambahi dengan bakso, pangsit, dan jamur. Mi berasal dari Tiongkok, tetapi mi ayam yang serupa di Indonesia tidak ditemukan di Tiongkok.[butuh rujukan] Mi ayam aslinya dari Tiongkok Selatan terutama dari daerah-daerah pelabuhan seperti Fujian dan Guandong.[butuh rujukan] Meskipun mi bukan asli Indonesia tapi nyatanya kini mi ayam seakan sudah menjadi makanan tradisional Indonesia. Makanan ini sudah tersebar di seluruh Indonesia, terutama di daerah Jawa makanan ini sangat mudah di temukan. Penjual mi ayam di Indonesia yang populer berasal dari Wonogiri.",
        "Mi goreng berarti mi yang digoreng adalah makanan yang berasal dari Indonesia yang populer dan juga digemari di Malaysia, dan Singapura. Mi goreng terbuat dari mi kuning yang digoreng dengan sedikit minyak goreng, dan ditambahkan bawang putih, bawang merah, udang serta daging ayam atau daging sapi, irisan bakso, cabai, sayuran, tomat, telur ayam, dan acar. Makanan ini sangat populer dan dapat ditemui di mana-mana di Indonesia, mulai dari pedagang pinggir jalan (kaki lima) sampai restoran mewah. Mi goreng juga dapat ditemukan di warung mamak di Malaysia dan Singapura. Versi mi instan dari mi goreng juga sangat populer, seperti Indomie Mi goreng. Masakan ini berasal dari Chow mein, mi China, dan dipercaya dibawa oleh para pendatang Cina ke Indonesia, Malaysia, and Singapura. Mi goreng juga mirip dengan Yakisoba dari Jepang. Akan tetapi mie goreng sudah sedemikian rupa terintegrasi ke dalam seni kuliner Indonesia. Sebagai contoh mie goreng membubuhkan kecap manis sebagai bahan penting. Untuk menyesuaikan dengan masyarakat Indonesia yang kebanyakan adalah muslim, mi goreng biasanya tidak menggunakan daging babi maupun lemak babi. Biasanya mi goreng menggunakan udang, daging ayam, atau daging sapi.",
        "Nasi goreng adalah sebuah makanan berupa nasi yang digoreng dan diaduk dalam minyak goreng, margarin, atau mentega. Biasanya ditambah kecap manis, bawang merah, bawang putih, asam jawa, lada dan bumbu-bumbu lainnya; seperti telur, ayam, dan kerupuk. Ada pula nasi goreng jenis lain yang dibuat bersama ikan asin yang juga populer di seluruh Indonesia. Nasi goreng juga dikenal sebagai masakan nasional Indonesia. Dari sekian banyak hidangan dalam khazanah Masakan Indonesia, hanya sedikit yang dapat dianggap sebagai makanan nasional sejati. Masakan nasional Indonesia ini tidak mengenal batasan kelas sosial. Nasi goreng dapat dinikmati secara sederhana di warung tepi jalan, gerobak penjaja keliling, hingga restoran dan meja prasmanan dalam pesta. Pada tahun 2011, sebuah polling Internet yang diadakan oleh CNN International dan diikuti oleh 35.000 orang menempatkan Nasi Goreng pada peringkat dua dalam daftar '50 Makanan Terlezat di Dunia' setelah rendang.",
        "Tekwan adalah penganan khas Palembang yang terbuat dari campuran daging ikan dan tapioka, yang dibentuk berupa bulatan kecil-kecil, dan disajikan dalam kuah udang dengan rasa yang khas. Biasanya pelengkap tekwan adalah sohun, irisan bengkoang dan jamur, serta ditaburi irisan daun bawang, seledri, dan bawang goreng. Tekwan berasal dari kata Berkotek Samo Kawan, yang dalam bahasa Palembang artinya duduk mengobrol bersama teman atau dari bahasa Min Selatan tê-kuàn (茶罐) yang berarti teko teh."
    )
    private val makananPhoto = intArrayOf(
        R.drawable.makanan_bakso,
        R.drawable.makanan_ayamgeprek,
        R.drawable.makanan_ayambakar,
        R.drawable.makanan_guramebakar,
        R.drawable.makanan_capcaygoreng,
        R.drawable.makanan_kwetiau,
        R.drawable.makanan_mieayam,
        R.drawable.makanan_miegoreng,
        R.drawable.makanan_nasigoreng,
        R.drawable.makanan_tekwan
    )

    val listData: ArrayList<Makanan>
        get() {
            val list = arrayListOf<Makanan>()
            for (i in makananNames.indices) {
                val makanan = Makanan()
                makanan.Name = makananNames[i]
                makanan.Price = makananPrice[i]
                makanan.Detail = makananDetail[i]
                makanan.Photo = makananPhoto[i]
                list.add(makanan)
            }
            return list
        }
}